# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
FROM neilpandya/pytorch:2.11.0-cu1281-cudnn9-ampere-znver3

# 1. Set environment variables
# Include `-march=znver3` here so any dependencies compiled by `uv` are optimized
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    MKL_THREADING_LAYER=GNU \
    OMP_NUM_THREADS=1 \
    TF_CPP_MIN_LOG_LEVEL=3 \
    CFLAGS="-march=znver3 -O3" \
    CXXFLAGS="-march=znver3 -O3"

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc git zip unzip wget curl htop libgl1 libglib2.0-0 gnupg libsm6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install 'uv' (Needs --break-system-packages)
RUN pip3 install --break-system-packages uv

# Prepare working directory and copy Ultralytics source
WORKDIR /ultralytics
COPY . .

# 6. Install Ultralytics and remaining dependencies
# uv needs BOTH --system AND --break-system-packages
RUN uv pip install --system --break-system-packages -e "." albumentations faster-coco-eval nvidia-ml-py wandb && \
    rm -rf tmp /root/.config/Ultralytics/persistent_cache.json

# Add official assets
ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
    /root/.config/Ultralytics/
